def build_case_data(
    case_id,
    case_type,
    client_type,
    client_name,
    registration_country,
    business_activity,
    bo_identified,
    bo_details,
    ultimate_controller,
    client_country,
    counterparty_countries,
    high_risk_geo,
    source_of_funds,
    transaction_amount,
    transaction_description,
    supporting_documents,
    purpose_of_relationship,
    product_or_service,
    economic_rationale,
    matches_profile,
    sanctions_result,
    pep_result,
    adverse_media_result,
    unresolved_issues,
    red_flags,
    mitigating_factors,
    key_risk_driver,
    risk_manageable,
    risk_level,
    recommendation,
    edd_required,
    decision_rationale,
    missing_info,
) -> dict:
    return {
        "case_id": case_id,
        "case_type": case_type,
        "client_type": client_type,
        "client_name": client_name,
        "registration_country": registration_country,
        "business_activity": business_activity,
        "beneficial_owner_identified": bo_identified,
        "beneficial_owner_details": bo_details,
        "ultimate_controller_description": ultimate_controller,
        "client_country": client_country,
        "counterparty_countries": [
            c.strip() for c in counterparty_countries.split(",") if c.strip()
        ],
        "high_risk_jurisdiction_involved": high_risk_geo,
        "source_of_funds_summary": source_of_funds,
        "transaction_amount": transaction_amount,
        "transaction_description": transaction_description,
        "supporting_documents_provided": supporting_documents,
        "purpose_of_relationship": purpose_of_relationship,
        "product_or_service_description": product_or_service,
        "economic_rationale_clear": economic_rationale,
        "matches_client_profile": matches_profile,
        "sanctions_result": sanctions_result,
        "pep_result": pep_result,
        "adverse_media_result": adverse_media_result,
        "unresolved_screening_issues": unresolved_issues,
        "red_flags_selected": [x.strip() for x in red_flags.splitlines() if x.strip()],
        "mitigating_factors_selected": [
            x.strip() for x in mitigating_factors.splitlines() if x.strip()
        ],
        "key_risk_driver": key_risk_driver,
        "risk_manageable": risk_manageable,
        "selected_risk_level": risk_level,
        "recommendation": recommendation,
        "edd_required": edd_required,
        "decision_rationale": decision_rationale,
        "missing_information_summary": missing_info,
    }